name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps
          npx playwright install-deps
        shell: bash
      - name: Start test server
        run: docker compose up --detach --wait app
      - name: Run fixture tests
        run: node test/test-fixtures.mjs || exit 1
      - name: Run Playwright tests
        run: npx playwright test
      - name: Run Python tests
        run: docker compose exec app poetry run python -m pytest

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          npm install
      - name: Build package
        run: python -m build
