name: Publish Python Package

on:
  release:
    types: [published]

concurrency:
  group: deploy-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps
          npx playwright install-deps
        shell: bash
      - name: Start test server
        run: docker compose up --detach --wait app
      - name: Run fixture tests
        run: node test/test-fixtures.mjs || exit 1
      - name: Run Playwright tests
        run: npx playwright test
      - name: Run Python tests
        run: docker compose exec app poetry run python -m pytest

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          npm install
      - name: Build package
        run: python -m build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  notify-slack:
    runs-on: ubuntu-latest
    needs:
      - deploy
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Get version number
        id: get-version
        run: |
          pip install -e .
          VERSION=$(python -c "import importlib.metadata; print(importlib.metadata.version('tna_frontend_jinja'))")
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Get the release notes
        id: release-notes
        run: |
          {
            echo 'RELEASE_NOTES<<EOF'
            ./.github/get-release-notes.sh ${STEPS_GET_VERSION_OUTPUTS_VERSION}
            echo EOF
          } >> "$GITHUB_OUTPUT"
        env:
          STEPS_GET_VERSION_OUTPUTS_VERSION: ${{ steps.get-version.outputs.VERSION }}
      - uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_TITLE: "`v${{ steps.get-version.outputs.VERSION }}` of `tna-frontend-jinja` has just been published"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: "https://raw.githubusercontent.com/nationalarchives/tna-frontend/main/src/nationalarchives/assets/images/icon-1024x1024.png"
          MSG_MINIMAL: true
          SLACKIFY_MARKDOWN: true
          SLACK_MESSAGE: ${{ steps.release-notes.outputs.RELEASE_NOTES }}
