name: Publish Python Package

on:
  release:
    types: [published]

concurrency:
  group: deploy-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages['node_modules/@playwright/test'].version)")" >> $GITHUB_ENV
        shell: bash
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Node dependencies
        run: npm ci
      - run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        shell: bash
      - run: npx playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        shell: bash
      - name: Start test server
        run: docker compose up --detach --wait app
      - name: Run fixture tests
        run: node test/test-fixtures.mjs || exit 1
      - name: Run Playwright tests
        run: npx playwright test
      - name: Run Python tests
        run: docker compose exec app poetry run python -m pytest

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          npm install
      - name: Build package
        run: python -m build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  notify-slack:
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - uses: actions/checkout@v6
      - name: Get version number
        id: get-version
        run: |
          pip install -e .
          VERSION=$(python -c "import importlib.metadata; print(importlib.metadata.version('tna_frontend_jinja'))")
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Get the release notes
        id: release-notes
        run: |
          {
            echo 'RELEASE_NOTES<<EOF'
            ./.github/get-release-notes.sh ${{ steps.get-version.outputs.VERSION }}
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: "`v${{ steps.get-version.outputs.VERSION }}` of `tna-frontend-jinja` has just been published"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: "https://raw.githubusercontent.com/nationalarchives/tna-frontend/main/src/nationalarchives/assets/images/icon-1024x1024.png"
          MSG_MINIMAL: true
          SLACKIFY_MARKDOWN: true
          SLACK_MESSAGE: ${{ steps.release-notes.outputs.RELEASE_NOTES }}
